assets:
- ticker: ALZR11
  path: ALZR11.xlsx
- ticker: BBAS3
  path: BBAS3.xlsx
- ticker: BBSE3
  path: BBSE3.xlsx
- ticker: BRAV3
  path: BRAV3.xlsx
- ticker: GGRC11
  path: GGRC11.xlsx
- ticker: HGRE11
  path: HGRE11.xlsx
- ticker: HGRU11
  path: HGRU11.xlsx
- ticker: HSML11
  path: HSML11.xlsx
- ticker: IRDM11
  path: IRDM11.xlsx
- ticker: ISAE4
  path: ISAE4.xlsx
- ticker: ITSA4
  path: ITSA4.xlsx
- ticker: JSRE11
  path: JSRE11.xlsx
- ticker: MOVI3
  path: MOVI3.xlsx
- ticker: MRVE3
  path: MRVE3.xlsx
- ticker: PRIO3
  path: PRIO3.xlsx
- ticker: SHUL4
  path: SHUL4.xlsx
- ticker: VAMO3
  path: VAMO3.xlsx
- ticker: VILG11
  path: VILG11.xlsx
- ticker: VISC11
  path: VISC11.xlsx
- ticker: VRTA11
  path: VRTA11.xlsx
- ticker: XPCI11
  path: XPCI11.xlsx
- ticker: XPML11
  path: XPML11.xlsx
benchmark:
- name: IBOV
  path: IBOV.xlsx
